### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by rveltz** [JuliaGPU/CLArrays.jl#26]
Hi,

Is there a command to monitor the amount of memory used by CLArrays variables?

Thank you for your help,

**Comment by davidbp** [comment]
You can use `sizeof`

```
julia>  A = [2,3,3]

julia> sizeof(A)
24

julia> A_gpu = CLArray(A)
GPU: 3-element Array{Int64,1}:
 2
 3
 3

julia> sizeof(A_gpu)
16
```

There is something that I don't get. I was assuming that CLArrays was casting my numbers to Float32/Int32 (and that was the reason size was halved) nevertheless they both seem to have the same `eltype`

```
julia> eltype(A_gpu)
Int64

julia> eltype(A)
Int64
```

**Comment by rveltz** [comment]
Thank you!

In fact, I hope hoping for something like `print_mem_info` in `ArrayFire` or something that gives the total memory allocated on the current device, for debugging purposes.

**Comment by davidbp** [comment]
@SimonDanisch  is there a way to check at a given moment what is  in GPU memory?  I don't know the internals and if CLArrays/GPUArrays takes care of garabage collection.I think it would be a very nice addition ro debugging and preventing memor problems when porting code.

**Comment by SimonDanisch** [comment]
Sadly it's not that easy. On NVIDIA hardware we can call CUDA directly for that, but since OpenCL tries (too) hard to hide underlying hardware, this seems only supported by calls to vendor extensions. We might want to add some AMD specific extensions here. It's not high on my priority list right now, so anyone googling and coming up with the right calls + PR is very welcome!

I just see, that for GC pressure I do actually track the memory allocated by CLArrays: You can query it with `CLArrays.current_allocated_mem[]`. It obviously will be incorrect, whenever any other program on your machine allocates something on the GPU.

The only GC related thing I do right now is trying to pressure the GC to free any gpu memory that's not referenced anymore:
https://github.com/JuliaGPU/CLArrays.jl/blob/master/src/memory.jl#L39

**Comment by davidbp** [comment]
I think you mean `Mem.current_allocated_mem[]`. I didn't know about it. It's quite useful. Probably this will be useful @rveltz     since it gives you at least the memory you are using on the device when using CLArrays. 

This snippet might help 
```
julia> X = CLArray(rand(10));
julia> sizeof(Array(X))
80
julia> Mem.current_allocated_mem[]
80
julia> Y = CLArray(rand(10));
julia> Mem.current_allocated_mem[]
160
julia> clear!(:Y)
julia> Mem.current_allocated_mem[]
80
```

**Comment by rveltz** [comment]
THHHHHHHX
